// <auto-generated />
using System;
using JobManager.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobManager.Migrations
{
    [DbContext(typeof(JobContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("JobManager.Models.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstimatedCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            ID = 22,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 1"
                        },
                        new
                        {
                            ID = 1,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 2"
                        },
                        new
                        {
                            ID = 2,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 3"
                        },
                        new
                        {
                            ID = 3,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 4"
                        },
                        new
                        {
                            ID = 4,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 5"
                        },
                        new
                        {
                            ID = 5,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 6"
                        },
                        new
                        {
                            ID = 6,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 7"
                        },
                        new
                        {
                            ID = 7,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 8"
                        },
                        new
                        {
                            ID = 8,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 9"
                        },
                        new
                        {
                            ID = 9,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 10"
                        },
                        new
                        {
                            ID = 10,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 11"
                        },
                        new
                        {
                            ID = 11,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 12"
                        },
                        new
                        {
                            ID = 12,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 13"
                        },
                        new
                        {
                            ID = 13,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 14"
                        },
                        new
                        {
                            ID = 14,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 15"
                        },
                        new
                        {
                            ID = 15,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 16"
                        },
                        new
                        {
                            ID = 16,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 17"
                        },
                        new
                        {
                            ID = 17,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 18"
                        },
                        new
                        {
                            ID = 18,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 19"
                        },
                        new
                        {
                            ID = 19,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 20"
                        },
                        new
                        {
                            ID = 20,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 21"
                        },
                        new
                        {
                            ID = 21,
                            Completed = false,
                            Description = "Task to be compleated.",
                            Priority = 1,
                            Title = "Task 22"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
